// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowFoodsApp.Repository;

#nullable disable

namespace WowFoodsApp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250327134119_CategoryAndProductsWithSeedData")]
    partial class CategoryAndProductsWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WowFoods.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Indian Street Food"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Chinese Street Food"
                        });
                });

            modelBuilder.Entity("WowFoods.Models.EmployeeStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStaffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfJoining = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Salary = 6000.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfJoining = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Salary = 8000.0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WowFoods.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("AddedBy");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AddedBy = 1,
                            CategoryId = 1,
                            Description = "Crispy puris filled with spicy water",
                            Name = "Pani Puri",
                            Price = 1.5m
                        },
                        new
                        {
                            ProductId = 2,
                            AddedBy = 1,
                            CategoryId = 1,
                            Description = "Fried pastry with savory filling",
                            Name = "Samosa",
                            Price = 1.0m
                        },
                        new
                        {
                            ProductId = 3,
                            AddedBy = 2,
                            CategoryId = 2,
                            Description = "Stir-fried noodles with vegetables",
                            Name = "Chow Mein",
                            Price = 5.0m
                        },
                        new
                        {
                            ProductId = 4,
                            AddedBy = 2,
                            CategoryId = 2,
                            Description = "Crispy rolls with vegetable filling",
                            Name = "Spring Rolls",
                            Price = 3.0m
                        });
                });

            modelBuilder.Entity("WowFoods.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            UserType = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123",
                            UserType = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WowFoods.Models.UserInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PhoneNumber = "1234567890",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@example.com",
                            FirstName = "Regular",
                            LastName = "User",
                            PhoneNumber = "0987654321",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WowFoods.Models.EmployeeStaff", b =>
                {
                    b.HasOne("WowFoods.Models.User", "User")
                        .WithOne("EmployeeStaff")
                        .HasForeignKey("WowFoods.Models.EmployeeStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowFoods.Models.Product", b =>
                {
                    b.HasOne("WowFoods.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowFoods.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowFoods.Models.UserInformation", b =>
                {
                    b.HasOne("WowFoods.Models.User", "User")
                        .WithOne("UserInformation")
                        .HasForeignKey("WowFoods.Models.UserInformation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WowFoods.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WowFoods.Models.User", b =>
                {
                    b.Navigation("EmployeeStaff");

                    b.Navigation("UserInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
